[versions]
# Implementation
activity = "1.2.4"
activityCompose = "1.3.1"
appcompat = "1.3.0"
compose = "1.0.1"
constraint = "2.0.4"
core = "1.6.0"
hiltx = "1.0.0"
hilt = "2.37"
desugaring = "1.0.9"
glide = "4.12.0"
fragment = "1.3.6"
jsonapi = "3.5.0"
kotlin = "1.5.21"
lifecycle = "2.3.1"
lifecycleCompose = "1.0.0-alpha07"
material = "1.5.0-alpha01"
moshi = "1.12.0"
multidex = "2.0.1"
navigation = "2.3.5"
retrofit = "2.9.0"
loggingInterceptor = "4.9.0"
rxAndroid = "3.0.0"
rxBinding = "4.0.0"
rxJava = "3.0.13"
rxKotlin = "3.0.1"
rxExt = "3.0.1"
security = "1.1.0-alpha03"
vector = "1.1.0"
viewPager2 = "1.0.0"

# Debug
detekt = "1.17.1"
leakCanary = "2.7"
stetho = "1.6.0"

# Test
archCoreTest = "2.1.0"
assertj = "3.20.2"
awaitility = "4.1.0"
espresso = "3.4.0"
junit = "4.13.2"
junitext = "1.1.2"
mockitoInline = "3.11.2"
mockitoKotlin = "3.2.0"
runner = "1.2.0"

# Classpath
gradle = "7.0.0"
googleServices = "4.3.10"
gradleVersionsPluginGradle = "0.33.0"
navigationSafeArgsPluginGradle = "2.3.5"
ktlintGradle = "10.0.0"

[libraries]
#### Implementation dependencies
# activity
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }

# appcompat
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

# compose
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
composeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "compose" }
composeMaterialIconsCore = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
composeRuntimeRx3 = { module = "androidx.compose.runtime:runtime-rxjava3", version.ref = "compose" }

# constraint
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint" }

# core
core = { module = "androidx.core:core", version.ref = "core" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "core" }

#fragment
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }

# glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

# hilt
hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompilerKapt = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hiltAndroidCompilerKapt = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltx" }

# jsonapi
jsonApi = { module = "moe.banana:moshi-jsonapi", version.ref = "jsonapi" }
jsonApiRetrofit = { module = "moe.banana:moshi-jsonapi-retrofit-converter", version.ref = "jsonapi" }

# kotlinStdLib
kotlinStdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

# lifecycle
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleReactiveKtx = { module = "androidx.lifecycle:lifecycle-reactivestreams-ktx", version.ref = "lifecycle" }
lifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleCompose" }

# material
material = { module = "com.google.android.material:material", version.ref = "material" }

# moshi
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshiCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

# multidex
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }

# navigation
navigationFragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigationUiKtx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

# retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitMoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofitRx3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
okHttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }

# rx
rxJava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxJava" }
rxAndroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxAndroid" }
rxKotlin = { module = "io.reactivex.rxjava3:rxkotlin", version.ref = "rxKotlin" }
rxJava3Extensions = { module = "com.github.akarnokd:rxjava3-extensions", version.ref = "rxExt" }

# security
security = { module = "androidx.security:security-crypto", version.ref = "security" }

# vector
vectordrawable = { module = "androidx.vectordrawable:vectordrawable", version.ref = "vector" }

#### Debug dependencies
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
stetho = { module = "com.facebook.stetho:stetho", version.ref = "stetho" }
stethoOkhttp3 = { module = "com.facebook.stetho:stetho-okhttp3", version.ref = "stetho" }

#### Test dependencies
# test
assertjCore = { module = "org.assertj:assertj-core", version.ref = "assertj" }
coreTesting = { module = "androidx.arch.core:core-testing", version.ref = "archCoreTest" }
junit = { module = "junit:junit", version.ref = "junit" }
mockitoInline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }

# androidTest
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
composeUiTest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espressoIntents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
junitExt = { module = "androidx.test.ext:junit", version.ref = "junitext" }
runner = { module = "androidx.test:runner", version.ref = "runner" }

### Classpath
detektPluginGradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
googleServices = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradleVersionsPluginGradle = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradleVersionsPluginGradle" }
hiltAndroidPluginGradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
kotlinPluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktlintGradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintGradle" }
navigationSafeArgsPluginGradle = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsPluginGradle" }

[bundles]
#### Implementation bundles
core = ["core", "coreKtx"]
compose = [
    "composeUi",
    "composeUiTooling",
    "composeFoundation",
    "composeMaterial",
    "composeMaterialIconsCore",
    "composeRuntimeRx3"
]
hiltKapt = ["hiltCompilerKapt", "hiltAndroidCompilerKapt"]
jsonApi = ["jsonApi", "jsonApiRetrofit"]
lifecycle = ["lifecycleRuntimeKtx", "lifecycleReactiveKtx"]
moshi = ["moshi", "moshiCodegen"]
navigation = ["navigationFragmentKtx", "navigationUiKtx"]
retrofit = [
    "retrofit",
    "retrofitMoshi",
    "retrofitRx3",
    "okHttpLogging"
]
rx = [
    "rxJava",
    "rxAndroid",
    "rxKotlin",
    "rxJava3Extensions",
]

#### Debug bundles
stetho = ["stetho", "stethoOkhttp3"]

#### Test bundles
espresso = ["espressoCore", "espressoIntents"]
mockito = ["mockitoInline", "mockitoKotlin"]
